#!/usr/bin/perl
use strict;
use warnings;

open(my $tsh, '<', $ARGV[0]) or die "Could not open file '$ARGV[0]' $!";
open(my $fh, '<', $ARGV[1]) or die "Could not open file '$ARGV[1]' $!";

my %timestamps_hash;
my $timestamps_key;
my @timestamps_vs;

# FIXME: '%-' from `srttrans`
while (my $line = <$tsh>) {
    chomp $line;
    if ($line =~ /^(\d+)%-/) {
        if (defined $timestamps_key) {
            $timestamps_hash{$timestamps_key} = [shift @timestamps_vs, join("\n", @timestamps_vs)];
        }
        $timestamps_key = $1;
        @timestamps_vs = ();
    } else {
        push @timestamps_vs, $line;
    }
}

if (defined $timestamps_key) {
    $timestamps_hash{$timestamps_key} = [shift @timestamps_vs, join("\n", @timestamps_vs)];
}

close $tsh;

my %hash;
my $key;
my $value = '';

while (my $line = <$fh>) {
    chomp $line;
    if ($line =~ /^(\d+)%-/) {
        if (defined $key) {
            $hash{$key} = $value;
        }
        $key = $1;
        $value = '';
    } else {
        $value .= "$line\n";
    }
}

if (defined $key) {
    $hash{$key} = $value;
}

close $fh;

foreach my $timestamps_key (sort { $a <=> $b } keys %timestamps_hash) {
    print "$timestamps_key\n";
    print "$timestamps_hash{$timestamps_key}->[0]\n";

    if (exists $hash{$timestamps_key}) {
        my $value = $hash{$timestamps_key};
        print "$value\n";
    } else {
        print "$timestamps_hash{$timestamps_key}->[1]\n";
    }
}
