#!/bin/bash

if [ $# -ne 2 ]; then
	>&2 echo "Please specify a LLM CLI and an option."
	>&2 echo 'For example: `'$0' deepl-cli KO` or `'$0' gemini-cli ko`'
	exit 1
fi

GRAY='\033[1;37m'
RED='\033[31m'
NOCOLOR='\033[0m'

TEMPFILE=$(mktemp)

SRT_TIMESTAMPS="$TEMPFILE"-TS
SRT_NUMERICS="$TEMPFILE"-NU
SRT_LLM="$TEMPFILE"-LLM

if [ "$(basename "$1")" = "deepl-cli" ]; then
	TARGET_LANG="$2"
else
	TARGET_LANG="translate to $2 without comment."
fi

function removetimestamps {
	# FIXME: '%-' is used in `srtmerge`
	srttidy -b | perl -0777 -pe 's/([0-9]+)\n([0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3} --> [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})/$1%-/g' | grep -v '^$'
}
function exitfn {
	trap SIGINT
	srtmerge $SRT_TIMESTAMPS $SRT_LLM
	rm $TEMPFILE*

	>&2 echo -e "${RED}Process interrupted. Translation partially completed. ${NOCOLOR}"
	exit 1
}

trap "exitfn" INT

export LT_VERBOSE="yes"

srttidy -by > $SRT_TIMESTAMPS
cat $SRT_TIMESTAMPS | removetimestamps > $SRT_NUMERICS
cat $SRT_NUMERICS | lt-llm-cli "$1" "$TARGET_LANG" > $SRT_LLM

if [ $? -ne 0 ]; then
	>&2 echo -e "${RED}Failed to translate the given SRT.${NOCOLOR}"
	exit 1
fi

srtmerge $SRT_TIMESTAMPS $SRT_LLM
rm $TEMPFILE*

>&2 echo -e "${GRAY}Translation compelted.${NOCOLOR}"
